export const FETCH_ALL_SYMBOLS = 'FETCH_ALL_SYMBOLS';
export const GET_SYMBOLS_REQUEST = 'GET_SYMBOLS_REQUEST';
export const GET_SYMBOLS_SUCCESS = 'GET_SYMBOLS_SUCCESS';
export const FETCH_QUOTES_FOR_SYMBOLS = 'FETCH_QUOTES_FOR_SYMBOLS';
export const POPULATE_QUOTES = 'POPULATE_QUOTES';
export const SELECTED_SYMBOLS = 'SELECTED_SYMBOLS';
export const DELETE_SYMBOL = 'DELETE_SYMBOL';
export const CLEAR_STATE = 'CLEAR_STATE';
export const POPULATE_LIST_QUOTES = 'POPULATE_LIST_QUOTES'

